
package it.parisnews.test.wb.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserRepositoryService", targetNamespace = "http://service.wb.test.parisnews.it/", wsdlLocation = "http://imac-di-francesco.local:8080/firstwebservice/UserRepositoryService?wsdl")
public class UserRepositoryService
    extends Service
{

    private final static URL USERREPOSITORYSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERREPOSITORYSERVICE_EXCEPTION;
    private final static QName USERREPOSITORYSERVICE_QNAME = new QName("http://service.wb.test.parisnews.it/", "UserRepositoryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://imac-di-francesco.local:8080/firstwebservice/UserRepositoryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERREPOSITORYSERVICE_WSDL_LOCATION = url;
        USERREPOSITORYSERVICE_EXCEPTION = e;
    }

    public UserRepositoryService() {
        super(__getWsdlLocation(), USERREPOSITORYSERVICE_QNAME);
    }

    public UserRepositoryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERREPOSITORYSERVICE_QNAME, features);
    }

    public UserRepositoryService(URL wsdlLocation) {
        super(wsdlLocation, USERREPOSITORYSERVICE_QNAME);
    }

    public UserRepositoryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERREPOSITORYSERVICE_QNAME, features);
    }

    public UserRepositoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserRepositoryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserRepository
     */
    @WebEndpoint(name = "UserRepositoryPort")
    public UserRepository getUserRepositoryPort() {
        return super.getPort(new QName("http://service.wb.test.parisnews.it/", "UserRepositoryPort"), UserRepository.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserRepository
     */
    @WebEndpoint(name = "UserRepositoryPort")
    public UserRepository getUserRepositoryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wb.test.parisnews.it/", "UserRepositoryPort"), UserRepository.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERREPOSITORYSERVICE_EXCEPTION!= null) {
            throw USERREPOSITORYSERVICE_EXCEPTION;
        }
        return USERREPOSITORYSERVICE_WSDL_LOCATION;
    }

}
